name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c贸digo
        uses: actions/checkout@v4

      - name: Configurar o JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Construir o projeto e rodar os testes
        run: mvn clean verify

      - name: Armazenar artefatos do build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/
          retention-days: 1

  coverage:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c贸digo
        uses: actions/checkout@v4

      - name: Configurar o JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Baixar artefatos do build
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: target/

      - name: Gerar relat贸rio de cobertura Jacoco
        run: mvn jacoco:report

      - name: Publicar relat贸rio de cobertura no GitHub
        uses: codecov/codecov-action@v4
        with:
          files: target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
          verbose: true
